name: CI
on:
  push:

env:
  DATABASE_URL: 'postgresql://worker:N7TOxwt83Nm@postgres:5432/app_db'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: 'worker'
          POSTGRES_PASSWORD: 'N7TOxwt83Nm'
          POSTGRES_DB: 'app_db'
          PGDATA: '/var/lib/postgresql/data/pgdata'
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.10'
        architecture: 'x64'

    - name: 'install'
      run: pip install -r ./src/requirements.txt

    - name: 'test'
      run: pytest ./src/tests
